const PRAYERS = {
candles:{title:'Shabbat Candle Lighting',lines:[['בָּרוּךְ אַתָּה יְיָ אֱלֹהֵינוּ מֶלֶךְ הָעוֹלָם, אֲשֶׁר קִדְּשָׁנוּ בְּמִצְוֹתָיו וְצִוָּנוּ לְהַדְלִיק נֵר שֶׁל שַׁבָּת.','Baruch atah Adonai, Eloheinu melech ha’olam, asher kid’shanu b’mitzvotav v’tzivanu l’hadlik ner shel Shabbat.']]},
wine:{title:'Borei P’ri Hagafen',lines:[['בָּרוּךְ אַתָּה יְיָ אֱלֹהֵינוּ מֶלֶךְ הָעוֹלָם, בּוֹרֵא פְּרִי הַגָּפֶן.','Baruch atah Adonai, Eloheinu melech ha’olam, borei p’ri hagafen.']]},
motzi:{title:'HaMotzi',lines:[['בָּרוּךְ אַתָּה יְיָ אֱלֹהֵינוּ מֶלֶךְ הָעוֹלָם, הַמּוֹצִיא לֶחֶם מִן הָאָרֶץ.','Baruch atah Adonai, Eloheinu melech ha’olam, hamotzi lechem min ha’aretz.']]},
modeh:{title:'Modeh Ani'},mahtovu:{title:'Mah Tovu'},
'shema-short':{title:'Shema and Baruch Shem',lines:[['שְׁמַע יִשְׂרָאֵל, יְיָ אֱלֹהֵינוּ, יְיָ אֶחָד.','Shema Yisrael, Adonai Eloheinu, Adonai echad.'],['בָּרוּךְ שֵׁם כְּבוֹד מַלְכוּתוֹ לְעוֹלָם וָעֶד.','Baruch shem k’vod malchuto l’olam va’ed.']]},
oseh:{title:'Oseh Shalom',note:'Nava Tehila melody',lines:[['עֹשֶׂה שָׁלוֹם בִּמְרוֹמָיו, הוּא יַעֲשֶׂה שָׁלוֹם עָלֵינוּ וְעַל כָּל יִשְׂרָאֵל, וְאִמְרוּ אָמֵן.','Oseh shalom bimromav, hu ya’aseh shalom aleinu v’al kol Yisrael, v’imru amen.']]},
barchu:{title:'Bar’chu',lines:[['בָּרְכוּ אֶת יְיָ הַמְבֹרָךְ.','Bar’chu et Adonai ham’vorach.'],['בָּרוּךְ יְיָ הַמְבֹרָךְ לְעוֹלָם וָעֶד.','Baruch Adonai ham’vorach l’olam va’ed.']]},
mi:{title:'Mi Chamocha',excerpt:true,lines:[['מִי כָמֹכָה בָּאֵלִם יְיָ, מִי כָּמֹכָה נֶאְדָּר בַּקֹּדֶשׁ, נוֹרָא תְהִלֹּת עֹשֵׂה פֶלֶא.','Mi chamocha ba’elim Adonai, mi kamocha ne’dar bakodesh, nora t’hilot, oseh fele.']]},
'adon-short':{title:'Adon Olam — First Verse',lines:[['אֲדוֹן עוֹלָם אֲשֶׁר מָלַךְ, בְּטֶרֶם כָּל יְצִיר נִבְרָא.','Adon olam asher malach, b’terem kol y’tzir nivra.'],['לְעֵת נַעֲשָׂה בְחֶפְצוֹ כֹּל, אֲזַי מֶלֶךְ שְׁמוֹ נִקְרָא.','L’et na’asah v’cheftzo kol, azai melech sh’mo nikra.']]},
mezonot:{title:'Mezonot'},sukkah:{title:'Blessing for Sitting in the Sukkah'},questions:{title:'The Four Questions'},matzah:{title:'Al Achilat Matzah'},aleinu:{title:'Aleinu'},hanukkah:{title:'Hanukkah Blessing'},birchot:{title:'Birchot Hashachar'},
'ashrei-short':{title:'Ashrei — First 8 Lines',excerpt:true,lines:[['אַשְׁרֵי יוֹשְׁבֵי בֵיתֶךָ, עוֹד יְהַלְלוּךָ סֶּלָה.','Ashrei yoshvei veitecha, od y’hal’lucha selah.'],['אַשְׁרֵי הָעָם שֶׁכָּכָה לּוֹ, אַשְׁרֵי הָעָם שֶׁיְיָ אֱלֹהָיו.','Ashrei ha’am shekachah lo, ashrei ha’am she’Adonai Elohav.'],['תְּהִלָּה לְדָוִד. אֲרוֹמִמְךָ אֱלוֹהַי הַמֶּלֶךְ, וַאֲבָרְכָה שִׁמְךָ לְעוֹלָם וָעֶד.','T’hilah l’David. Aromimcha Elohai hamelech, va’avar’chah shimcha l’olam va’ed.'],['בְּכָל יוֹם אֲבָרְכֶךָּ, וַאֲהַלְלָה שִׁמְךָ לְעוֹלָם וָעֶד.','B’chol yom avar’cheka, va’hal’lah shimcha l’olam va’ed.'],['גָּדוֹל יְיָ וּמְהֻלָּל מְאֹד, וְלִגְדֻלָּתוֹ אֵין חֵקֶר.','Gadol Adonai um’hulal m’od, v’ligdulato ein cheker.'],['דּוֹר לְדוֹר יְשַׁבַּח מַעֲשֶׂיךָ, וּגְבוּרֹתֶיךָ יַגִּידוּ.','Dor l’dor y’shabach ma’asecha, ug’vurotecha yagidu.'],['הֲדַר כְּבוֹד הוֹדֶךָ, וְדִבְרֵי נִפְלְאֹתֶיךָ אָשִׂיחָה.','Hadar k’vod hodecha, v’divrei nifl’otecha asichah.'],['וֶעֱזוּז נוֹרְאֹתֶיךָ יֹאמֵרוּ, וּגְדֻלָּתְךָ אֲסַפְּרֶנָּה.','Ve’ezuz nor’otecha yomeru, ug’dulat’cha asap’renah.']]},
psalm150:{title:'Hallelujah — Psalm 150',lines:[['הַלְלוּיָהּ. הַלְלוּ אֵל בְּקָדְשׁוֹ, הַלְלוּהוּ בִּרְקִיעַ עֻזּוֹ.','Hal’luyah. Hal’lu El b’kodsho, hal’luhu birkia uzo.'],['הַלְלוּהוּ בִגְבוּרֹתָיו, הַלְלוּהוּ כְּרֹב גֻּדְלוֹ.','Hal’luhu vigvurotav, hal’luhu k’rov gudlo.'],['הַלְלוּהוּ בְּתֵקַע שׁוֹפָר, הַלְלוּהוּ בְּנֵבֶל וְכִנּוֹר.','Hal’luhu b’teka shofar, hal’luhu b’nevel v’chinor.'],['הַלְלוּהוּ בְתֹף וּמָחוֹל, הַלְלוּהוּ בְּמִנִּים וְעוּגָב.','Hal’luhu v’tof umachol, hal’luhu b’minim v’ugav.'],['הַלְלוּהוּ בְצִלְצְלֵי שָׁמַע, הַלְלוּהוּ בְּצִלְצְלֵי תְרוּעָה.','Hal’luhu v’tziltz’lei shama, hal’luhu b’tziltz’lei t’ruah.'],['כֹּל הַנְּשָׁמָה תְּהַלֵּל יָהּ, הַלְלוּיָהּ.','Kol han’shamah t’hallel Yah, hal’luyah.']]},
shema:{title:'Shema and V’ahavta',lines:[['שְׁמַע יִשְׂרָאֵל, יְיָ אֱלֹהֵינוּ, יְיָ אֶחָד.','Shema Yisrael, Adonai Eloheinu, Adonai echad.'],['בָּרוּךְ שֵׁם כְּבוֹד מַלְכוּתוֹ לְעוֹלָם וָעֶד.','Baruch shem k’vod malchuto l’olam va’ed.'],['וְאָהַבְתָּ אֵת יְיָ אֱלֹהֶיךָ, בְּכָל לְבָבְךָ וּבְכָל נַפְשְׁךָ וּבְכָל מְאֹדֶךָ.','V’ahavta et Adonai Elohecha, b’chol l’vav’cha uv’chol nafsh’cha uv’chol m’odecha.'],['וְהָיוּ הַדְּבָרִים הָאֵלֶּה אֲשֶׁר אָנֹכִי מְצַוְּךָ הַיּוֹם עַל לְבָבֶךָ.','V’hayu had’varim ha’eleh asher anochi m’tzav’cha hayom al l’vavecha.'],['וְשִׁנַּנְתָּם לְבָנֶיךָ וְדִבַּרְתָּ בָּם, בְּשִׁבְתְּךָ בְּבֵיתֶךָ וּבְלֶכְתְּךָ בַדֶּרֶךְ וּבְשָׁכְבְּךָ וּבְקוּמֶךָ.','V’shinantam l’vanecha v’dibarta bam, b’shivt’cha b’veitecha uv’lecht’cha vaderech uv’shochb’cha uv’kumecha.'],['וּקְשַׁרְתָּם לְאוֹת עַל יָדֶךָ, וְהָיוּ לְטֹטָפֹת בֵּין עֵינֶיךָ.','Uk’shartam l’ot al yadecha, v’hayu l’totafot bein einecha.'],['וּכְתַבְתָּם עַל מְזֻזוֹת בֵּיתֶךָ וּבִשְׁעָרֶיךָ.','Uch’tavtam al m’zuzot beitecha uvish’arecha.']]},
avot:{title:'Amidah — Avot',excerpt:true,lines:[['בָּרוּךְ אַתָּה יְיָ, אֱלֹהֵינוּ וֵאלֹהֵי אֲבוֹתֵינוּ, אֱלֹהֵי אַבְרָהָם, אֱלֹהֵי יִצְחָק, וֵאלֹהֵי יַעֲקֹב.','Baruch atah Adonai, Eloheinu v’Elohei avoteinu, Elohei Avraham, Elohei Yitzchak, v’Elohei Ya’akov.']]},
adon:{title:'Adon Olam',excerpt:true},einkeloheinu:{title:'Ein Keloheinu'},
shehecheyanu:{title:'Shehecheyanu',lines:[['בָּרוּךְ אַתָּה יְיָ אֱלֹהֵינוּ מֶלֶךְ הָעוֹלָם, שֶׁהֶחֱיָנוּ וְקִיְּמָנוּ וְהִגִּיעָנוּ לַזְּמַן הַזֶּה.','Baruch atah Adonai, Eloheinu melech ha’olam, shehecheyanu v’kiy’manu v’higianu laz’man hazeh.']]},
vshamru:{title:'V’shamru',note:'Friday night melody',lines:[['וְשָׁמְרוּ בְנֵי יִשְׂרָאֵל אֶת הַשַּׁבָּת, לַעֲשׂוֹת אֶת הַשַּׁבָּת לְדֹרֹתָם בְּרִית עוֹלָם.','V’shamru v’nei Yisrael et haShabbat, la’asot et haShabbat l’dorotam b’rit olam.'],['בֵּינִי וּבֵין בְּנֵי יִשְׂרָאֵל אוֹת הִיא לְעֹלָם, כִּי שֵׁשֶׁת יָמִים עָשָׂה יְיָ אֶת הַשָּׁמַיִם וְאֶת הָאָרֶץ, וּבַיּוֹם הַשְּׁבִיעִי שָׁבַת וַיִּנָּפַשׁ.','Beini uvein b’nei Yisrael ot hi l’olam, ki sheshet yamim asah Adonai et hashamayim v’et ha’aretz, uvayom hash’vii shavat vayinafash.']]},
food:{title:'HaMotzi and Mezonot'},shehakol:{title:'Shehakol'},fruit:{title:'Ha’adama and Ha’etz'},netilah:{title:'N’tilat Yadayim'},havdalah:{title:'Havdalah'},ashrei:{title:'Ashrei — Full Recording',excerpt:true},
shochein:{title:'Shochein Ad',lines:[['שׁוֹכֵן עַד מָרוֹם וְקָדוֹשׁ שְׁמוֹ.','Shochein ad, marom v’kadosh sh’mo.'],['וְכָתוּב: רַנְּנוּ צַדִּיקִים בַּיְיָ, לַיְשָׁרִים נָאוָה תְהִלָּה.','V’chatuv: ran’nu tzadikim ba’Adonai, lay’sharim navah t’hilah.'],['בְּפִי יְשָׁרִים תִּתְהַלָּל, וּבְדִבְרֵי צַדִּיקִים תִּתְבָּרַךְ.','B’fi y’sharim tit’halal, uv’divrei tzadikim tit’barach.'],['וּבִלְשׁוֹן חֲסִידִים תִּתְרוֹמָם, וּבְקֶרֶב קְדוֹשִׁים תִּתְקַדָּשׁ.','Uvilshon chasidim tit’romam, uv’kerev k’doshim tit’kadash.']]},
yishtabach:{title:'Yishtabach',excerpt:true,lines:[['יִשְׁתַּבַּח שִׁמְךָ לָעַד מַלְכֵּנוּ, הָאֵל הַמֶּלֶךְ הַגָּדוֹל וְהַקָּדוֹשׁ בַּשָּׁמַיִם וּבָאָרֶץ.','Yishtabach shimcha la’ad malkeinu, ha’El hamelech hagadol v’hakadosh bashamayim uva’aretz.']]},
kaddish:{title:'Hatzi Kaddish',excerpt:true,lines:[['יִתְגַּדַּל וְיִתְקַדַּשׁ שְׁמֵהּ רַבָּא.','Yitgadal v’yitkadash sh’mei raba.'],['בְּעָלְמָא דִּי בְרָא כִרְעוּתֵהּ, וְיַמְלִיךְ מַלְכוּתֵהּ בְּחַיֵּיכוֹן וּבְיוֹמֵיכוֹן וּבְחַיֵּי דְכָל בֵּית יִשְׂרָאֵל, בַּעֲגָלָא וּבִזְמַן קָרִיב, וְאִמְרוּ אָמֵן.','B’alma di v’ra chirutei, v’yamlich malchutei b’chayeichon uv’yomeichon uv’chayei d’chol beit Yisrael, ba’agala uvizman kariv, v’imru amen.'],['יְהֵא שְׁמֵהּ רַבָּא מְבָרַךְ לְעָלַם וּלְעָלְמֵי עָלְמַיָּא.','Y’hei sh’mei raba m’varach l’alam ul’almei almaya.']]},
yotzer:{title:'Yotzer Or / Or Chadash',excerpt:true,lines:[['אוֹר חָדָשׁ עַל צִיּוֹן תָּאִיר, וְנִזְכֶּה כֻלָּנוּ מְהֵרָה לְאוֹרוֹ.','Or chadash al Tzion ta’ir, v’nizkeh chulanu m’herah l’oro.'],['בָּרוּךְ אַתָּה יְיָ, יוֹצֵר הַמְּאוֹרוֹת.','Baruch atah Adonai, yotzer ham’orot.']]},
eladon:{title:'El Adon',excerpt:true,lines:[['אֵל אָדוֹן עַל כָּל הַמַּעֲשִׂים, בָּרוּךְ וּמְבֹרָךְ בְּפִי כָּל נְשָׁמָה.','El adon al kol hama’asim, baruch um’vorach b’fi kol n’shamah.'],['גָּדְלוֹ וְטוּבוֹ מָלֵא עוֹלָם, דַּעַת וּתְבוּנָה סוֹבְבִים הוֹדוֹ.','Godlo v’tuvo malei olam, da’at ut’vunah sov’vim hodo.']]},
vehaer:{title:'V’ha’er Eineinu',lines:[['וְהָאֵר עֵינֵינוּ בְּתוֹרָתֶךָ, וְדַבֵּק לִבֵּנוּ בְּמִצְוֹתֶיךָ, וְיַחֵד לְבָבֵנוּ לְאַהֲבָה וּלְיִרְאָה אֶת שְׁמֶךָ.','V’ha’er eineinu b’Toratecha, v’dabek libeinu b’mitzvotecha, v’yached l’vaveinu l’ahavah ul’yirah et sh’mecha.'],['וְלֹא נֵבוֹשׁ לְעוֹלָם וָעֶד.','V’lo nevosh l’olam va’ed.']]},
'mi-shira':{title:'Mi Chamocha and Shira Chadashah'},tzur:{title:'Tzur Yisrael'},gevurot:{title:'Amidah — G’vurot'},kedushah:{title:'Amidah — Kedushah'},einkamocha:{title:'Ein Kamocha'},avharachamim:{title:'Av Harachamim'},vayehi:{title:'Vayehi Binsoa Ha’aron / Ki Mitzion'},torah:{title:'Shema, Echad, Gadlu'},lcha:{title:'L’cha Adonai / Romemu'},aliyah:{title:'Aliyah Blessings'},vayechulu:{title:'Vayechulu / Borei P’ri Hagafen'},'ein-aleinu':{title:'Ein Keloheinu and Aleinu'},anim:{title:'Anim Zemirot',note:'Melody 1',excerpt:true,lines:[['אָנִים זְמִירוֹת וְשִׁירִים אֶאֱרֹג, כִּי אֵלֶיךָ נַפְשִׁי תַעֲרֹג.','Anim z’mirot v’shirim e’erog, ki eilecha nafshi ta’arog.'],['נַפְשִׁי חָמְדָה בְּצֵל יָדֶךָ, לָדַעַת כָּל רָז סוֹדֶךָ.','Nafshi chamdah b’tzel yadecha, lada’at kol raz sodecha.']]}
};
PRAYERS.adon.lines=PRAYERS['adon-short'].lines;PRAYERS.ashrei.lines=PRAYERS['ashrei-short'].lines;
const CLASSES={
'K-1':{cols:4,rows:4,grid:[1.2,14,97.5,74.5],items:['candles','wine','motzi','modeh','mahtovu','shema-short','oseh','barchu','mi','adon-short','mezonot','sukkah','questions','matzah','aleinu','hanukkah'],extra:['shehecheyanu']},
'2-3':{cols:4,rows:5,grid:[2,13.7,96.4,73.4],items:['birchot','ashrei-short','psalm150','barchu','shema','mi','avot','adon','einkeloheinu','aleinu','shehecheyanu','sukkah','vshamru','food','shehakol','fruit','questions','matzah','netilah','havdalah']},
'4-5':{cols:5,rows:5,grid:[1.2,14.1,97.5,78.1],items:['ashrei','psalm150','shochein','yishtabach','kaddish','barchu','yotzer','eladon','vehaer','shema','mi-shira','tzur','avot','gevurot','kedushah','vshamru','einkamocha','avharachamim','vayehi','torah','lcha','aliyah','vayechulu','ein-aleinu','anim']}
};
